/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        "on-tertiary": "#650911",
        "secondary-container": "#0566d9",
        "on-secondary": "#002e6a",
        "surface-container-high": "#242c27",
        "on-primary-fixed-variant": "#005236",
        "surface": "#0e1511",
        "inverse-surface": "#dde4dd",
        "background": "#0e1511",
        "on-primary-fixed": "#002113",
        "on-tertiary-fixed": "#410005",
        "error-container": "#93000a",
        "on-error": "#690005",
        "surface-dim": "#0e1511",
        "on-background": "#dde4dd",
        "primary-fixed": "#6ffbbe",
        "primary-container": "#10b981",
        "surface-container-low": "#161d19",
        "on-error-container": "#ffdad6",
        "surface-tint": "#4edea3",
        "primary": "#4edea3",
        "tertiary": "#ffb3af",
        "on-primary-container": "#00422b",
        "on-secondary-fixed-variant": "#004395",
        "on-primary": "#003824",
        "error": "#ffb4ab",
        "secondary-fixed": "#d8e2ff",
        "on-tertiary-fixed-variant": "#842225",
        "surface-container-lowest": "#09100c",
        "primary-fixed-dim": "#4edea3",
        "on-surface": "#dde4dd",
        "secondary-fixed-dim": "#adc6ff",
        "surface-variant": "#2f3632",
        "surface-container-highest": "#2f3632",
        "inverse-on-surface": "#2b322d",
        "on-secondary-fixed": "#001a42",
        "tertiary-fixed-dim": "#ffb3af",
        "outline": "#86948a",
        "tertiary-fixed": "#ffdad7",
        "on-secondary-container": "#e6ecff",
        "outline-variant": "#3c4a42",
        "secondary": "#adc6ff",
        "on-tertiary-container": "#711419",
        "surface-bright": "#343b36",
        "on-surface-variant": "#bbcabf",
        "surface-container": "#1a211d",
        "inverse-primary": "#006c49",
        "tertiary-container": "#fc7c78",
        "finza-surface": "#1E293B",
        "finza-bg": "#0F172A",
        "finza-border": "rgba(255, 255, 255, 0.1)"
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      spacing: {
        "xs": "8px",
        "gutter": "20px",
        "xl": "64px",
        "md": "24px",
        "margin-desktop": "48px",
        "margin-mobile": "16px",
        "sm": "16px",
        "lg": "40px",
        "base": "4px"
      },
      fontFamily: {
        sans: ['Inter', 'sans-serif'],
      }
    },
  },
  plugins: [],
}
